name: eps-conda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy>=1.22
      - pandas>=1.3
      - matplotlib>=3.5
      - scikit-learn>=1.0
      - gpflow>=2.5
      - tensorflow>=2.15
      - absl-py>=1.0
      - jax>=0.4.13
      - jaxlib>=0.4.13
      - plotly>=5.0
      - ipykernel>=6.0
      - -e .
